version: '3.7'

services:
  web:
    build: ./app
    volumes:
      - ./app/:/usr/src/app/
    expose:
      - 8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django

  nginx:
    image: nginx:1.15-alpine
    restart: always
    ports:
        - 80:80
        - 443:443
    volumes:
        - ./app/hidonash/static:/static/
        - ./nginx:/etc/nginx/conf.d
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    depends_on:
         - web

volumes:
  postgres_data:
