# Generated by Django 4.2.3 on 2023-07-14 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('home', '0003_homepage_body'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomePage',
            new_name='Epk',
        ),
    ]
