# Generated by Django 4.2.3 on 2023-07-14 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_homepage_epk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='epk',
            old_name='body',
            new_name='bio_field',
        ),
    ]
