# Generated by Django 4.2.3 on 2023-07-14 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_body_epk_bio_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='epk',
            old_name='bio_field',
            new_name='bio',
        ),
    ]
